shared:
  image: chef/chefdk:current

jobs:
  main:
    steps:
      - exact: sd-step exec --pkg-version "2.7.4" core/git "git --version"
      - childa: sd-step exec --pkg-version "~2.7.0" core/git "git --version"
      - hat: sd-step exec --pkg-version "^2.7.0" core/git "git --version"
      - notfound: sd-step exec --pkg-version "3.7.0" core/git "git --version"
